/**
 * Shadow Coach processor — closes the learning loop after each session.
 *
 * Reads:
 *   - The Shadow Coach JSON report generated by Claude after every conversation
 *   - The optional <phase_progress> tag emitted when phase_day hits exit-signal day
 *
 * Writes (idempotent):
 *   - mse_personal_dictionary       — words used in real context this session
 *   - mse_visceral_milestones       — milestone unlocked (first dream, joke, etc.)
 *   - mse_real_life_missions        — mark today's mission as completed
 *   - mse_novel_chapters            — mark current chapter as completed if advanced
 *   - mse_student_profiles          — tiempo_de_boca counter, recurring_errors merge
 *   - mse_phase_progress (via recordPhaseTransition) when ready_to_advance
 *
 * The bot's master prompt v2 is the contract for the report shape — see
 * master-prompt.ts "OUTPUT FORMAT" section for the canonical schema.
 */
import {
  addTiempoDeBoca,
  completeChapter,
  completeTodayMission,
  getLatestChapter,
  getStudentProfile,
  recordPhaseTransition,
  recordVisceralMilestone,
  recordWordLearned,
  updateStudentProfile,
} from "./db";
import { hasExitSignal, nextPhase, phaseCompletionPct } from "./phase-engine";
import type { CunaPhase, VisceralMilestoneKey } from "./phase-engine";

// =====================================================================
// Types — what the bot is contracted to emit
// =====================================================================

export type ShadowCoachReport = {
  session_summary?: string;
  ritual_slot?: string;
  minutos_de_boca?: number;
  highlights?: string[];
  errors_detected?: Array<{
    error?: string;
    correction?: string;
    explanation_es?: string;
    phase_appropriate_to_correct?: boolean;
  }>;
  new_vocabulary_introduced?: string[];
  vocabulary_used_in_real_context?: string[];
  personal_facts_learned?: string[];
  novel_chapter_advanced?: boolean;
  mission_completed?: boolean;
  visceral_milestone_candidate?: VisceralMilestoneKey | null;
  next_session_recommendation?: string | null;
};

export type PhaseProgressTag = {
  current_phase?: number;
  phase_completion_pct?: number;
  exit_signal_met?: boolean;
  exit_signal_evidence?: string;
  ready_to_advance?: boolean;
  visceral_milestone_unlocked?: string | null;
  celebration_message_es?: string;
};

export type ProcessSessionResult = {
  words_dictionary_added: number;
  milestone_unlocked: VisceralMilestoneKey | null;
  mission_completed: boolean;
  chapter_completed: boolean;
  tiempo_de_boca_added: number;
  phase_advanced_to: CunaPhase | null;
  celebration_es: string | null;
};

// =====================================================================
// Validators
// =====================================================================

const VALID_MILESTONES: ReadonlySet<VisceralMilestoneKey> = new Set<VisceralMilestoneKey>([
  "first_dream_in_english",
  "first_thought_without_translation",
  "first_joke_landed",
  "first_native_understood_first_try",
  "first_word_in_real_life",
  "first_30sec_no_spanish",
  "first_60sec_no_spanish",
  "first_full_conversation_5min",
  "first_podcast_understood",
  "first_series_no_subs",
  "sello_cuna_completed",
]);

function isValidMilestone(k: unknown): k is VisceralMilestoneKey {
  return typeof k === "string" && VALID_MILESTONES.has(k as VisceralMilestoneKey);
}

function isValidPhase(p: unknown): p is CunaPhase {
  return typeof p === "number" && Number.isInteger(p) && p >= 0 && p <= 5;
}

// =====================================================================
// Main processor
// =====================================================================

export async function processSessionEnd(opts: {
  userId: string;
  report: ShadowCoachReport;
  phaseProgress: PhaseProgressTag | null;
  sessionSummary: string;
}): Promise<ProcessSessionResult> {
  const { userId, report, phaseProgress, sessionSummary } = opts;

  const result: ProcessSessionResult = {
    words_dictionary_added: 0,
    milestone_unlocked: null,
    mission_completed: false,
    chapter_completed: false,
    tiempo_de_boca_added: 0,
    phase_advanced_to: null,
    celebration_es: null,
  };

  // We need the profile early to know current_phase + for merge of legacy fields.
  const profile = await getStudentProfile(userId);
  if (!profile) {
    // Defensive: no profile → nothing to record against.
    return result;
  }

  // ── 1. Tiempo de boca ───────────────────────────────────────────
  if (typeof report.minutos_de_boca === "number" && report.minutos_de_boca > 0) {
    const seconds = Math.round(report.minutos_de_boca * 60);
    await addTiempoDeBoca(userId, seconds);
    result.tiempo_de_boca_added = seconds;
  }

  // ── 2. Personal dictionary — words USED in real context this session ──
  const wordsToRecord = (report.vocabulary_used_in_real_context ?? [])
    .filter((w): w is string => typeof w === "string" && w.trim().length > 0);
  for (const word of wordsToRecord) {
    await recordWordLearned({
      userId,
      word,
      context: sessionSummary || "(sin contexto)",
      phase: profile.current_phase,
    });
    result.words_dictionary_added++;
  }

  // ── 3. Mission completed ────────────────────────────────────────
  if (report.mission_completed === true) {
    await completeTodayMission({ userId });
    result.mission_completed = true;
  }

  // ── 4. Novel chapter advanced ───────────────────────────────────
  if (report.novel_chapter_advanced === true) {
    const latest = await getLatestChapter(userId);
    if (latest && latest.completed_at === null) {
      // Mark as completed without student audio — that's a separate flow.
      await completeChapter(latest.id, latest.student_part_audio_url ?? "");
      result.chapter_completed = true;
    }
  }

  // ── 5. Visceral milestone candidate from Shadow Coach report ────
  if (isValidMilestone(report.visceral_milestone_candidate)) {
    const newlyRecorded = await recordVisceralMilestone({
      userId,
      milestoneKey: report.visceral_milestone_candidate,
      context: sessionSummary,
    });
    if (newlyRecorded) result.milestone_unlocked = report.visceral_milestone_candidate;
  }

  // ── 6. Visceral milestone from <phase_progress> tag (more authoritative) ──
  if (phaseProgress?.visceral_milestone_unlocked && isValidMilestone(phaseProgress.visceral_milestone_unlocked)) {
    const newlyRecorded = await recordVisceralMilestone({
      userId,
      milestoneKey: phaseProgress.visceral_milestone_unlocked,
      context: phaseProgress.exit_signal_evidence ?? sessionSummary,
    });
    if (newlyRecorded && !result.milestone_unlocked) {
      result.milestone_unlocked = phaseProgress.visceral_milestone_unlocked;
    }
  }

  // ── 7. Phase transition (most consequential — gated) ────────────
  if (phaseProgress?.ready_to_advance === true) {
    const target = nextPhase(profile.current_phase);
    if (target !== null) {
      // Re-validate exit signal server-side using current state of milestones.
      // This guards against premature advancement if Sofia is over-eager.
      const milestonesSet = new Set<VisceralMilestoneKey>();
      if (isValidMilestone(phaseProgress.visceral_milestone_unlocked)) {
        milestonesSet.add(phaseProgress.visceral_milestone_unlocked);
      }
      if (isValidMilestone(report.visceral_milestone_candidate)) {
        milestonesSet.add(report.visceral_milestone_candidate);
      }

      const serverSideOk = hasExitSignal({
        phase: profile.current_phase,
        phaseDay: profile.phase_day,
        visceralMilestonesAchieved: Array.from(milestonesSet),
      });

      if (serverSideOk) {
        await recordPhaseTransition({
          userId,
          fromPhase: profile.current_phase,
          toPhase: target,
          exitSignalEvidence: phaseProgress.exit_signal_evidence,
          completionPct: phaseProgress.phase_completion_pct ?? phaseCompletionPct(profile.current_phase, profile.phase_day),
        });
        result.phase_advanced_to = target;
      }
    }
  }

  // ── 8. Celebration message ──────────────────────────────────────
  if (typeof phaseProgress?.celebration_message_es === "string") {
    result.celebration_es = phaseProgress.celebration_message_es;
  }

  // ── 9. Legacy field merging (kept — still useful) ───────────────
  const existingErrors = (profile.recurring_errors as unknown[]) ?? [];
  const newErrors = (report.errors_detected ?? []).filter(
    (e) => e && (e.error || e.correction)
  );
  const mergedErrors = [...existingErrors, ...newErrors].slice(-10);

  const personalFactsExisting = profile.personal_facts ?? {};
  const newFacts = report.personal_facts_learned ?? [];
  const personalFactsMerged: Record<string, unknown> = { ...personalFactsExisting };
  newFacts.forEach((f, i) => {
    if (typeof f === "string" && f.trim()) {
      personalFactsMerged[`fact_${Date.now()}_${i}`] = f;
    }
  });

  await updateStudentProfile(userId, {
    recurring_errors: mergedErrors,
    personal_facts: personalFactsMerged,
    last_session_summary: sessionSummary,
  });

  return result;
}
